#######################################################################################
#  Custom Weapon Sound Plugin                                                         #
#  Created by Jb06                                                      		  #
#                                                                      			  #
#######################################################################################
#                                                                                     #
import Foundation
import App
#                                                                                     #
#######################################################################################
#      

Foundation.SoundDef("sfx/Weapons/JLS_tricobolt.wav", "JLSTricobaltDevice", 1)
Foundation.SoundDef("sfx/Weapons/JLSintrepid_phaser_a.wav", "IntrPhaser Start", 1)
Foundation.SoundDef("sfx/Weapons/JLSintrepid_phaser_b.wav", "IntrPhaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/ZZ_KlingonTMP2.wav", "VoyPhoton", 1.0)
Foundation.SoundDef("sfx/Weapons/JLSBTa.wav", "JLSBorgTorp", 1.0)
Foundation.SoundDef("sfx/Weapons/ChrotonBurst.wav", "Burst Start", 2)
Foundation.SoundDef("sfx/Weapons/ChrotonBursta.wav", "Burst Loop", 2)
Foundation.SoundDef("sfx/AeonEngines.wav", "Aeon Engine", 0.8)
Foundation.SoundDef("sfx/Weapons/Caretaker.wav", "Caretaker Array", 1)
Foundation.SoundDef("sfx/Weapons/8472Beam.wav", "8472 Start", 2)
Foundation.SoundDef("sfx/Weapons/8472Beam.wav", "8472 Loop", 2)
Foundation.SoundDef("sfx/8472Engine.wav", "8472 Engine", 0.8)
Foundation.SoundDef("sfx/Weapons/Nanoprobe.wav", "Nanoprobe", 1)
Foundation.SoundDef("sfx/Weapons/JLSnphaser_a.wav", "JLSNihydron Phaser Start", 1)
Foundation.SoundDef("sfx/Weapons/JLSnphaser_b.wav", "JLSNihydron Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSncannon.wav", "JLSNihydron Disruptor", 1)
Foundation.SoundDef("sfx/Weapons/JLSntorpedo.WAV", "JLSNihydron Torpedo", 1)
Foundation.SoundDef("sfx/JLSnihyengine.wav", "JLSNihydron Engines", 0.7)
Foundation.SoundDef("sfx/Weapons/JLSmaw_phaser_a.wav", "JLS Mawasi Phaser Start", 1)
Foundation.SoundDef("sfx/Weapons/JLSmaw_phaser_b.wav", "JLS Mawasi Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSMawasiTorp.wav", "JLSMawasi Torpedo", 1)
Foundation.SoundDef("sfx/JLSMawasiEngines.wav", "JLSMawasi Engines", 0.8)
Foundation.SoundDef("sfx/Weapons/JLSZahl_Phaser_a.wav", "JLSZahl Phaser Start", 1)
Foundation.SoundDef("sfx/Weapons/JLSZahl_Phaser_b.wav", "JLSZahl Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSZahlTorp.wav", "JLSZahl Torpedo", 1)
Foundation.SoundDef("sfx/IntrepidEngines.wav", "IntrepidEngines", 0.8)
Foundation.SoundDef("sfx/Weapons/JLSRaven_phaser_a.wav", "Raven Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSRaven_phaser_b.wav", "Raven Phaser Loop", 2)
Foundation.SoundDef("sfx/Weapons/Kazon_phaser_a.wav", "JLSKazonPhaser Start", 1)
Foundation.SoundDef("sfx/Weapons/Kazon_phaser_b.wav", "JLSKazonPhaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/KazonTorpedo.wav", "KazonTorpedo", 1)
Foundation.SoundDef("sfx/Weapons/JLSborg phaser1a.wav", "JLSBorg Phaser Start", 1)
Foundation.SoundDef("sfx/Weapons/JLSborg phaser2a.wav", "JLSBorg Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSBTa.wav", "JLSBT", 1)
Foundation.SoundDef("sfx/Weapons/JLSBT1a.wav", "JLSBT1", 1)
Foundation.SoundDef("sfx/Weapons/JLSBorgTraca.wav", "JLSBorgTrac", 1)
Foundation.SoundDef("sfx/Weapons/JLSBorgCutter_A.wav", "JLSBorgCutters Start", 1.0)
Foundation.SoundDef("sfx/Weapons/JLSBorgCutter_B.wav", "JLSBorgCutters Loop", 1.0)
Foundation.SoundDef("sfx/JLSBorg.wav", "JLSBorg", 0.8)
Foundation.SoundDef("sfx/Weapons/JLSQuantum.wav", "JLSQuantum", 1)
Foundation.SoundDef("sfx/Weapons/JLSNovaPhaser_a.wav", "JLSNova Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSNovaPhaser_b.wav", "JLSNova Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSBomarT.wav", "JLSBomarSnd", 1)
Foundation.SoundDef("sfx/Weapons/JLSBPhaser_a.wav", "JLSBo Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSBPhaser_b.wav", "JLSBo Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLS8472Torp.wav", "JLS8472Torp", 1)
Foundation.SoundDef("sfx/Weapons/JLSTalBeam_a.wav", "JLSTal Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSTalBeam_b.wav", "JLSTal Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSTaTorp.wav", "JLSTTorp", 1)
Foundation.SoundDef("sfx/Weapons/JLSKrenimP.wav", "JLSKrenimP", 1)
Foundation.SoundDef("sfx/Weapons/JLSKrenimBeam_a.wav", "JLSKrenim Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSKrenimBeam_b.wav", "JLSKrenim Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSNightBeam_a.wav", "JLSNight Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSNightBeam_b.wav", "JLSNight Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSNightTorp.wav", "JLSNightTorp", 1)
Foundation.SoundDef("sfx/Weapons/JLSVaadwaur.wav", "JLSVaadwaur", 1)
Foundation.SoundDef("sfx/Weapons/JLSHirogenP.wav", "JLSHirogenP", 1)
Foundation.SoundDef("sfx/Weapons/JLSVidiianTorp.wav", "JLSVidiianTorp", 1)
Foundation.SoundDef("sfx/Weapons/JLSVidiianPulse.wav", "JLSVidiianP", 1)
Foundation.SoundDef("sfx/Weapons/JLSDralianPhaser_a.wav", "JLS Dralian Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSDralianPhaser_b.wav", "JLS Dralian Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSReptoPhaser_a.wav", "JLS Repto Phaser Start", 2)
Foundation.SoundDef("sfx/Weapons/JLSReptoPhaser_b.wav", "JLS Repto Phaser Loop", 1)
Foundation.SoundDef("sfx/Weapons/JLSNygeanTorp.wav", "JLSNygeanTorp", 1)
Foundation.SoundDef("sfx/Weapons/JLSKrenimChroniton.wav", "JLSKrenimChroniton", 1)
Foundation.SoundDef("sfx/JLSThinkEngines.wav", "Think Engines", 0.8)
Foundation.SoundDef("sfx/Weapons/JLSDevorePulse.wav", "JLSDevoreP", 1)
Foundation.SoundDef("sfx/Weapons/JLSDevoreTorp.wav", "JLSDevoreTorp", 1)
#                                                                                     #
#######################################################################################
