lActiveMutators = [
	"""Sneaker98's MVAM Infinite""",
	"""NanoFX v2.0 BETA""",
	"""Stock Systems""",
	"""Promellian""",
	"""AI auto Warping""",
	"""Per Bridge Loading screen""",
	"""Extra Ships and Mods""",
	"""Sneaker98's Bridge Menu Scroller""",
	"""Thrusters""",
	"""BCS:TNG WalkFX KM Edition""",
	"""Random Crew Reports""",
	"""MLeoDaalder's Detail/Nit Fix""",
	"""Nemesis Collisions""",
	"""Advanced Power control""",
	"""Stock Ships""",
	"""QBautostart Extension V1.0""",
	"""Skinning And Damaging Tool""",
	"""Alternate Nemesis Music""",
	"""Construct Mod""",
	"""USS Frontier's GravityFX""",
	"""StarfleetOperations-Cardassia""",
	"""Allow Surrender""",
	"""Sol""",
	"""AI Shuttle Launching""",
	"""AI Abandon Ship""",
	"""BCS:TB: Silent Running""",
	"""DS9FX Xtended""",
	"""BanzaiZAP SystemPack""",
	"""CJMP System Maps in Quick Battle""",
	"""Foundation Technologies""",
	"""ZMSystemPack""",
	"""Auto switch Bridge""",
	"""3E's Bridge Menu Enlarger""",
	"""Blind Firing""",
	"""USS Frontier's Galaxy Charts""",
	"""BCS:TB: Emergency Repair""",
	"""BCS:TB: Targetable Plasma Streams""",
	"""New Technology System""",
	"""Planet Classification Script""",
	"""BCS:TB: Assimilation Beam""",
]
